name: Cron and Action Workflow-ex5

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes

    steps:
      - uses: actions/checkout@v4
      - name: Run Greet Action
        id: greet_step
        uses: ./.github/actions/greet_people
        with:
          names: 'Engineers'
      - name: Conditional Step that should succeed
        if: ${{ steps.greet_step.outputs.greeted_names == 'Engineers and 1 more person' }}
        run: echo "Conditional step"