name: CI/CD Pipeline
on:
 pull_request:
   branches:
     - master
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
     - name: Log in to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build Docker image
       run: docker build -t your-dockerhub-username/your-repo-name:latest .
     - name: Push Docker image
       run: docker push your-dockerhub-username/your-repo-name:latest
 deploy:
   needs: build
   runs-on: ubuntu-latest
   environment: dev
   steps:
     - name: Deploy to Development
       run: echo "Deploying to development environment"
       env:
         DEPLOY_ENV: dev
 deploy-int:
   needs: build
   runs-on: ubuntu-latest
   environment: int
   steps:
     - name: Deploy to Integration
       run: echo "Deploying to integration environment"
       env:
         DEPLOY_ENV: acc
 deploy-prg:
   needs: build
   runs-on: ubuntu-latest
   environment: prg
   steps:
     - name: Deploy to Production
       run: echo "Deploying to production environment"
       env:
         DEPLOY_ENV: prod